construct_site_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name = 'construct_site_food'

urlpatterns = [
	path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('apply-promocode/', views.ApplyPromoCodeView.as_view(),
		name='apply_promocode'),
	path('<slug:slug>/', views.ClientIndexView.as_view(), name='client'),
	path('<slug:slug>/construct/', views.ConstructIndexView.as_view(),
		name='construct'),
	path('<slug:slug>/good/create/', views.GoodCreateView.as_view(),
		name='good_create'),
	path('<slug:slug>/good/delete/<int:pk>', views.GoodDeleteView.as_view(),
		name='good_delete'),
	path('<slug:slug>/good/update/<int:pk>', views.GoodUpdateView.as_view(),
		name='good_update'),
	path('<slug:slug>/category/create/', views.CategoryCreateView.as_view(),
		name='category_create'),
	path('<slug:slug>/category/delete/<int:pk>', views.CategoryDeleteView.as_view(),
		name='category_delete'),
	path('<slug:slug>/category/update/<int:pk>', views.CategoryUpdateView.as_view(),
		name='category_update'),
	path('good/<int:id>/add/to/cart', views.GoodAddToCart.as_view(),
		name='good_add_to_cart'),
	path('good/<int:id>/remove/from/cart', views.GoodRemoveFromCart.as_view(),
		name='good_remove_from_cart'),
	path('order/page/<slug:slug>', views.OrderView.as_view(),
		name='order_page'),
	path('order/good/', views.OrderGoodView.as_view(),
		name='order_good'),
	path('good/list/<slug:slug>/<int:category>/',
		views.GoodListView.as_view(), name='good_list'),

]


gosite/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
	url('', include('pwa.urls')),
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
    	redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', include('account.urls')),
    path('construct/site/', include('construct_site.urls')),
    path('', include('construct_site_food.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

cart/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from construct_site_food.models import Good
from decimal import Decimal


class PromoCode(models.Model):
    code = models.CharField(max_length=50, unique=True)
    uses_limit = models.PositiveIntegerField(default=1)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'), blank=True,
                                              null=True)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'), blank=True,
                                          null=True)

    def __str__(self):
        return self.code

    def is_valid_for_user(self, user):
        """Проверяет, может ли пользователь использовать этот промокод."""
        if not self.is_active or (self.end_date is not None and self.end_date < timezone.now()):
            return False

        user_usage = self.userpromocodeusage_set.filter(user=user).first()
        if user_usage and user_usage.uses_count >= self.uses_limit:
            return False

        return True

    def use_by_user(self, user):
        """Регистрирует использование промокода пользователем."""
        if self.is_valid_for_user(user):
            user_usage, created = UserPromoCodeUsage.objects.get_or_create(promo_code=self, user=user)
            user_usage.uses_count += 1
            user_usage.save()
            return True
        return False


class UserPromoCodeUsage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.CASCADE)
    uses_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} - {self.promo_code.code}"


class Order(models.Model):
    STATUS_CHOICES = (
        ('accepted', 'Заказ принят'),
        ('in_progress', 'Заказ делается'),
        ('courier', 'Передан курьеру'),
        ('delivered', 'Доставлен'),
        ('arrived', 'Прибыл'),
    )
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='accepted')
    delivery_time = models.DateTimeField(default=timezone.now() + timezone.timedelta(minutes=50))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('0.00'))
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost_before_discount(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_discount(self):
        """Возвращает сумму скидки в зависимости от типа скидки."""
        total_cost = self.get_total_cost_before_discount()
        if self.discount_percentage > 0:
            discount = (self.discount_percentage / Decimal('100.0')) * total_cost
        else:
            discount = self.discount_amount
        return discount.quantize(Decimal('0.01'))

    def get_total_cost(self):
        """Возвращает итоговую стоимость заказа с учетом скидки."""
        total_cost = self.get_total_cost_before_discount()
        discount = self.get_discount()
        return (total_cost - discount).quantize(Decimal('0.01'))


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    good = models.ForeignKey(Good,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.id)
    def get_cost(self):
        return self.price * self.quantity


templates/construct_site_food/foodoma/order/order_detail.html
<h2>Заказ №{{ order.id }}</h2>
    <p>Статус: {{ order.get_status_display }}</p>
    <p>Время доставки: {{ order.delivery_time }}</p>

    <h3>Детали заказа</h3>
    <ul>
        {% for item in order.items.all %}
            <li>{{ item.good.name }} - Количество: {{ item.quantity }} - Цена: {{ item.get_cost }}</li>
        {% endfor %}
    </ul>

    <p>Итоговая стоимость: {{ order.get_total_cost }}</p>

templates/construct_site_food/foodoma/order/order_list.html



<html lang="en" class="" style="">
   <head>
      {% load static %}
      {% load food_tags %}
	   <title></title>
	   <meta charset="utf-8">
	   <meta http-equiv="cache-control" content="no-cache">
	   <meta http-equiv="expires" content="0">
	   <meta http-equiv="pragma" content="no-cache">
	   <meta name="theme-color" content="#fff">
	   <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
      <link rel="stylesheet" type="text/css" href="{% static 'css/construct_site_food/main.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/construct_site_food/style.css' %}">
	</head>
   <body cz-shortcut-listen="true" class="bg-grey">
      <div id="page-container">
         <div id="root">
            {% csrf_token %}
            <span>
               <div>
                  <div class="col-12 p-0 fixed" style="z-index: 9;">
                     <div class="block m-0">
                        <div class="block-content p-0 undefined">
                           <div class="input-group search-box">
                              <div class="input-group-prepend">
                                 <a href="{% url 'construct_site_food:client' slug='nurdaulett' %}" class="btn search-navs-btns undefined" style="padding-top: 18px;">
                                    <svg class="arrow-right-3" viewBox="0 0 5 9">
                                        <path d="M0.419,9.000 L0.003,8.606 L4.164,4.500 L0.003,0.394 L0.419,0.000 L4.997,4.500 L0.419,9.000 Z" />
                                    </svg>
                                 </a>
                              </div>
                              <p class="form-control search-input d-flex align-items-center undefined"><span class="nav-page-title">Мои заказы</span></p>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="pt-50 bg-white">

                  </div>
                  <h2 class="item-text mb-10">История заказов</h2>
                  {% for order in orders %}
                  <div class="p-15">
                     <div class="block-content block-content-full bg-white pt-10 pb-5">


                              <div class="cart-item-meta pt-15 pb-15 align-items-center quantity-content">
                                 <div class="cart-item-name">
                                    <span class="false">
                                       <strong>Заказ №{{ order.id }}</strong><br>
                                       <strong>{{ order.get_status_display }}</strong>
                                    </span>
                                 </div>
                                 <div class="btn-group btn-group-sm cart-item-btn">
                                     <br> <div id="timer{{ order.id }}" class="timer" data-end-time="{{ order.delivery_time|date:'c' }}"></div>

                                 </div>
                                 <div class="cart-item-price">
                                    {{order.get_total_cost}} ₸
                                 </div>
                              </div>
                        <h3>Детали заказа</h3>
    <ul>
        {% for item in order.items.all %}
            <li>{{ item.good.title }} - Количество: {{ item.quantity }} - Цена: {{ item.get_cost }}</li>
        {% endfor %}
    </ul>

                     </div>
                  </div>
                  {% endfor %}
               </div>
            </span>
         </div>
      </div>
   </body>
   <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/js.cookie.min.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const timers = document.querySelectorAll('.timer');

    timers.forEach(function(timer) {
        const endTime = new Date(timer.getAttribute('data-end-time')).getTime();

        const updateTimer = function() {
            const now = new Date().getTime();
            const distance = endTime - now;

            if (distance < 0) {
                clearInterval(interval);
                timer.innerHTML = 'Доставлено';
                return;
            }

            const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((distance % (1000 * 60)) / 1000);

            timer.innerHTML = hours + 'ч ' + minutes + 'м ' + seconds + 'с ';
        };

        // Обновляем таймер каждую секунду
        let interval = setInterval(updateTimer, 1000);
        updateTimer(); // Инициализируем сразу при загрузке
    });
});
</script>

</html>