construct_site_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name = 'construct_site_food'

urlpatterns = [
	path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('apply-promocode/', views.ApplyPromoCodeView.as_view(),
		name='apply_promocode'),
	path('<slug:slug>/', views.ClientIndexView.as_view(), name='client'),
	path('<slug:slug>/construct/', views.ConstructIndexView.as_view(),
		name='construct'),
	path('<slug:slug>/good/create/', views.GoodCreateView.as_view(),
		name='good_create'),
	path('<slug:slug>/good/delete/<int:pk>', views.GoodDeleteView.as_view(),
		name='good_delete'),
	path('<slug:slug>/good/update/<int:pk>', views.GoodUpdateView.as_view(),
		name='good_update'),
	path('<slug:slug>/category/create/', views.CategoryCreateView.as_view(),
		name='category_create'),
	path('<slug:slug>/category/delete/<int:pk>', views.CategoryDeleteView.as_view(),
		name='category_delete'),
	path('<slug:slug>/category/update/<int:pk>', views.CategoryUpdateView.as_view(),
		name='category_update'),
	path('good/<int:id>/add/to/cart', views.GoodAddToCart.as_view(),
		name='good_add_to_cart'),
	path('good/<int:id>/remove/from/cart', views.GoodRemoveFromCart.as_view(),
		name='good_remove_from_cart'),
	path('order/page/<slug:slug>', views.OrderView.as_view(),
		name='order_page'),
	path('order/good/', views.OrderGoodView.as_view(),
		name='order_good'),
	path('good/list/<slug:slug>/<int:category>/',
		views.GoodListView.as_view(), name='good_list'),

]


gosite/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
	url('', include('pwa.urls')),
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
    	redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', include('account.urls')),
    path('construct/site/', include('construct_site.urls')),
    path('', include('construct_site_food.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

construct_site_food/models.py
import contextlib
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFill
from account.models import UserSite

# Базовый mixin
class BaseMixin(models.Model):
    title = models.CharField(max_length=180)

    def __str__(self):
        return self.title

    class Meta:
    	abstract = True


# Список категории
class Category(BaseMixin):
    user_site = models.ForeignKey(
    	UserSite, on_delete=models.CASCADE,
    	null=True, blank=True,
    	related_name='category_user_sites')
    color = models.CharField(max_length=120, default="#fc8019")
    sorting = models.IntegerField(default=0)


#Список товаров
class Good(BaseMixin):
    title = models.CharField(max_length=120, null=True, blank=True)
    description = models.TextField(blank=True)
    price = models.CharField(max_length=120, blank=True, default='')
    old_price = models.CharField(max_length=120, blank=True, default='')
    photo = ProcessedImageField(upload_to='images/',
                                processors=[ResizeToFill(317, 231)],
                                format='JPEG',
                                options={'quality': 100})
    category = models.ForeignKey(Category,
    	on_delete=models.SET_NULL, null=True, blank=True)
    user_site = models.ForeignKey(
    	UserSite, on_delete=models.CASCADE,
    	related_name='good_user_sites', null=True, blank=True)
    sorting = models.IntegerField(default=0)

construct_site_food/forms.py
from string import Template
from django import forms
from django.forms import ImageField
from .models import Good


class GoodForm(forms.ModelForm):
    photo = ImageField(widget=forms.FileInput)

    class Meta:
        model = Good
        fields = (
            'title', 'price', 'old_price', 'photo',
            'category', 'description'
        )

construct_site_food/views.py
import base64
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.core.files.base import ContentFile
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView
from django.views.generic.base import TemplateResponseMixin, View
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from account.models import UserSite
from construct_site.models import Support, AdditionalData
from cart.forms import CartAddProductForm
from cart.cart import Cart
from .models import Good, Category
from django.utils import timezone
from cart.models import PromoCode, Order, OrderItem, UserPromoCodeUsage
from .forms import GoodForm
from decimal import Decimal


# Mixin для передачи url как дополнительный параметр
class UrlMixin:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url'] = self.request.GET.get('url', None)
        return context

# Mixin для отображения сообщении об успешном завершении
class DeleteMixin:

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        data = super().delete(request, *args, **kwargs)
        messages.success(self.request, self.success_message % obj.__dict__)
        return data

# Mixin товара
class GoodMixin(SuccessMessageMixin):
    model = Good
    form_class = GoodForm

    def get_success_url(self):
        slug = self.kwargs.get('slug')
        kwargs = {'slug': slug}
        return reverse_lazy('construct_site_food:construct', kwargs = kwargs)


# Mixin редактирования товара
class GoodEditMixin(GoodMixin, UrlMixin):
    template_name = 'construct_site_food/construct/good/form.html'

    def form_valid(self, form):
        slug = self.kwargs.get('slug')
        user_site = get_object_or_404(UserSite, slug=slug, user=self.request.user)
        obj = form.save(commit=False)
        obj.user_site = user_site
        obj.save()
        return super().form_valid(form)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        slug = self.kwargs.get('slug')
        form.fields['category'].queryset = Category.objects.filter(
            user_site__slug=slug)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# Создать товар
class GoodCreateView(LoginRequiredMixin, GoodEditMixin, CreateView):
    success_message = "Товар успешно добавлен!"


# Обновить товар
class GoodUpdateView(LoginRequiredMixin, GoodEditMixin, UpdateView):
    success_message = "Товар успешно обновлен!"


# Удалить товар
class GoodDeleteView(
    LoginRequiredMixin,GoodMixin, UrlMixin, DeleteMixin, DeleteView):
    template_name = 'construct_site_food/construct/good/delete.html'
    success_message = "Товар успешно удален!"


# Mixin категорию
class CategoryMixin(SuccessMessageMixin):
    model = Category
    fields = ['title', 'sorting', 'color']

    def get_success_url(self):
        slug = self.kwargs.get('slug')
        return reverse_lazy('construct_site_food:construct', kwargs = {'slug':slug})


# Mixin редактирования категорию
class CategoryEditMixin(CategoryMixin, UrlMixin):
    template_name = 'construct_site_food/construct/category/form.html'

    def form_valid(self, form):
        slug = self.kwargs.get('slug')
        user_site = get_object_or_404(UserSite, slug=slug, user=self.request.user)
        obj = form.save(commit=False)
        obj.user_site = user_site
        obj.save()
        return super().form_valid(form)

# Создать категорию
class CategoryCreateView(
    LoginRequiredMixin, CategoryEditMixin, CreateView):
    success_message = "Категория успешно добавлена!"


# Обновить категорию
class CategoryUpdateView(
    LoginRequiredMixin, CategoryEditMixin, UpdateView):
    success_message = "Категория успешно обновлена!"


# Удалить категорию
class CategoryDeleteView(
    LoginRequiredMixin, CategoryMixin, DeleteMixin, UrlMixin, DeleteView):
    template_name = 'construct_site_food/construct/category/delete.html'
    success_message = "Категория успешно удалена!"

# Дополнительные данные создать или обновить
class AdditionalDataCreatOrUpdateView(View):

    def post(self, request, slug):
        user_site = get_object_or_404(UserSite, slug=slug, user=request.user)
        element_id = request.POST.get('element_id')
        photo = request.FILES.get('photo', None)
        value = request.POST.get('value', None)
        obj, created = AdditionalData.objects.get_or_create(
            element_id = element_id,
            user_site=user_site,
            defaults = {
                'value':value, 'element_id': element_id,
                'photo': photo, 'user_site': user_site
            }
        )
        if not created:
            obj.photo = photo
            obj.value = value
            obj.element_id = element_id
            obj.slug = user_site
            obj.save()
        return HttpResponse('saved')


# Дополнительные данные удалить
class AdditionalDataDelete(LoginRequiredMixin, View):

    def post(self, request, slug):
        element_id = request.POST.get('element_id')
        AdditionalData.objects.filter(element_id=element_id,
        	user_site__slug=slug).delete()
        return HttpResponse('deleted')


# Страница конструктора
class ConstructIndexView(LoginRequiredMixin, GoodMixin, ListView):
    template_name = 'construct_site_food/construct/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        category = self.kwargs.get('category', None)
        user_site = get_object_or_404(
            UserSite, slug=slug, user=self.request.user)
        categories = Category.objects.filter(user_site__slug=slug)
        goods = Good.objects.filter(user_site__slug=slug)
        supports = Support.objects.filter(user_site__slug=slug)
        context['user_site'] = user_site
        context['slug'] = slug
        context['categories'] = categories
        context['goods'] = goods
        context['supports'] = supports
        
        return context


# Страница клиента
class ClientIndexView(GoodMixin, View):

    def get(self, request, **kwargs):
        context = {}
        slug = self.kwargs.get('slug')
        categories = Category.objects.filter(
            user_site__slug=slug).select_related().order_by('-sorting')
        supports = Support.objects.filter(user_site__slug=slug)
        goods = Good.objects.filter(user_site__slug=slug).order_by('-sorting')
        if categories.exists():
            category = self.kwargs.get('category', None)
            if not  category:
                category = categories.first().id
            goods = goods.filter(category=category)
            context['active_category'] = category
        user_site = get_object_or_404(UserSite, slug=slug)
        context['slug'] = slug
        context['categories'] = categories
        context['goods'] = goods
        context['supports'] = supports
        context['user_site'] = user_site
        context['manifest_file'] = '/manifest/' + str(slug) + '.json'
        return render(request, user_site.site.template_name, context)


class GoodToCartMixin(View):

    def dispatch(self, *args, **kwargs):
        good_id = self.kwargs.get('id')
        self.cart = Cart(self.request)
        self.good = get_object_or_404(Good, id=good_id)
        return super().dispatch(*args, **kwargs)

# товарить товар в корзину
class GoodAddToCart(GoodToCartMixin):

    def post(self, request, *args, **kwargs):
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            self.cart.add(product=self.good,
                quantity=cd['quantity'],
                decrement=cd['decrement'])
            if self.cart.get_good(self.good):
                quantity = self.cart.get_good(self.good).get('quantity')
            else:
                quantity = 0
            return JsonResponse({
                'status': True,
                'quantity': quantity,
                'total_items': self.cart.get_items(),
                'total_price': self.cart.get_total_price()

            })
        return JsonResponse({'status': False})


# товарить товар в корзину
class GoodRemoveFromCart(GoodToCartMixin):

    def post(self, request, *args, **kwargs):
        self.cart.remove(self.good)
        return JsonResponse({'status': True})


# страница заказа
class OrderView(TemplateResponseMixin, View):
    template_name = 'construct_site_food/foodoma/order.html'

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return self.render_to_response({'slug': slug})

    def post(self, request, *args, **kwargs):
        return self.render_to_response({})

# заказать товар
class OrderGoodView(View):

    def post(self, request, *args, **kwargs):
        delivery_address = request.POST.get('delivery_address', '')
        promocode_code = request.POST.get('promocode', '')
        user = request.user
        cart = Cart(request)

        # Проверка и применение промокода
        discount_amount = Decimal('0.00')
        if promocode_code:
            try:
                promocode = PromoCode.objects.get(code=promocode_code, is_active=True, start_date__lte=timezone.now(),

templates/construct_site_food/foodoma/order.html
<html lang="en" class="" style="">
   <head>
      {% load static %}
      {% load food_tags %}
	   <title></title>
	   <meta charset="utf-8">
	   <meta http-equiv="cache-control" content="no-cache">
	   <meta http-equiv="expires" content="0">
	   <meta http-equiv="pragma" content="no-cache">
	   <meta name="theme-color" content="#fff">
	   <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
      <link rel="stylesheet" type="text/css" href="{% static 'css/construct_site_food/main.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/construct_site_food/style.css' %}">
	</head>
   <body cz-shortcut-listen="true" class="bg-grey">
      <div id="page-container">
         <div id="root">
            {% csrf_token %}
            <span>
               <div>
                  <div class="col-12 p-0 fixed" style="z-index: 9;">
                     <div class="block m-0">
                        <div class="block-content p-0 undefined">
                           <div class="input-group search-box">
                              <div class="input-group-prepend">
                                 <a href="{% url 'construct_site_food:client' slug %}" class="btn search-navs-btns undefined" style="padding-top: 18px;">
                                    <svg class="arrow-right-3" viewBox="0 0 5 9">
                                        <path d="M0.419,9.000 L0.003,8.606 L4.164,4.500 L0.003,0.394 L0.419,0.000 L4.997,4.500 L0.419,9.000 Z" />
                                    </svg>
                                 </a>
                              </div>
                              <p class="form-control search-input d-flex align-items-center undefined"><span class="nav-page-title">Корзина</span></p>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="pt-50 bg-white">
                        
                  </div>
                  <div class="p-15">
                     <div class="block-content block-content-full bg-white pt-10 pb-5">
                        <h2 class="item-text mb-10">Выбранные продукты</h2>
                        {% for item in cart %}
                           {% get_food_good item.id as good %}
                           {% if good %}
                              <div class="cart-item-meta pt-15 pb-15 align-items-center quantity-content">
                                 <div class="cart-item-name">
                                    <span class="false">
                                       <strong>{{good.title}}</strong>
                                    </span>
                                 </div>
                                 <div class="btn-group btn-group-sm cart-item-btn">
                                    <button type="button" class="btn btn-add-remove remove-to-cart" data-id="{{good.id}}" data-url="{% url 'construct_site_food:good_add_to_cart' id=good.id %}">
                                       <span class="btn-dec">-</span>
                                       <canvas height="0" width="0"></canvas>
                                    </button>
                                    <button type="button" id="quantity-show-{{good.id}}" class="btn btn-quantity quantity-show" data-price="{{good.price}}">
                                       {{item.quantity}}
                                    </button>
                                    <button type="button" class="btn btn-add-remove add-to-cart" data-id="{{good.id}}" data-url="{% url 'construct_site_food:good_add_to_cart' id=good.id %}">
                                       <span class="btn-inc">+</span>
                                       <canvas height="0" width="0" ></canvas>
                                    </button>
                                 </div>
                                 <div class="cart-item-price">
                                    {{item.price}} ₸
                                 </div>
                              </div>
                           {% endif %}
                        {% endfor %}
                     </div>
                     <input id="delivery-address" class="form-control order-comment" type="text" placeholder="Введите адрес доставки" value="">

                  </div>
                  <div>
                     <div class="px-15">
                        <div class="bg-white bill-details mb-200 border-radius-4px">   
                           <div class="p-15">
                              <div style="display:flex">
                                       <input id="promocode" class="form-control order-comment" type="text" placeholder="Введите промокод" value="">
                                       <input type="submit" value="применить" id="check-promo">
                                    </div>
                              <div class="display-flex">
                                 <div class="flex-auto font-w700">К оплате</div>
                                 <div class="flex-auto text-right font-w700">

                                    <span id="output-price-sum">{{cart.get_total_price}}</span> ₸
                                 </div> 
                              </div>

                           </div>
                        </div>
                     </div>
                  </div>

                  <div class="bg-white cart-checkout-block">
                     <div class="p-15">
                        <!--h2 class="almost-there-text m-0 pb-5">Almost There</h2>
                        <span class="almost-there-sub text-muted">Login or Signup to place your order</span-->
                        <button class="btn btn-lg btn-continue order-good">
                           Заказать
                           <canvas height="0" width="0" ></canvas>
                        </button>
                     </div>
                  </div>
               </div>
            </span>
         </div>
      </div>
   </body>
   <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/js.cookie.min.js' %}"></script>
   <script src="{% static 'js/cart.js' %}"></script>
   <script type="text/javascript">
      var csrftoken = Cookies.get('csrftoken')
      function csrfSafeMethod(method) {
         // these HTTP methods do not require CSRF protection
         return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
         beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
               xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
         }
      })
      $(document).on("click", ".order-good", function(e) {
         var delivery_address = $('#delivery-address').val()
         var promocode = $('#promocode').val()
         $.ajax({
            url: "{% url 'construct_site_food:order_good' %}",
            type: 'POST',
            data:{
               delivery_address: delivery_address,
               promocode: promocode
            },
            error: function(jqXHR, textStatus, errorThrown) {
               alert(jqXHR.responseText)
               console.log(jqXHR.responseText)
            },
            success:function (data) {
               alert(data)
            }
         })
      })

      $(document).on("click", "#check-promo", function(e) {
         var promocode = $('#promocode').val()
         var total_sum = $('#output-price-sum').text()
         $.ajax({
            url: "{% url 'construct_site_food:apply_promocode' %}",
            type: 'GET',
            data:{
               promocode: promocode,
               total_sum:total_sum
            },
            error: function(jqXHR, textStatus, errorThrown) {
               alert(errorThrown)
               console.log(jqXHR.responseText)
            },
            success:function (data) {
               $('#output-price-sum').html(data.discount)
            }
         })
      })
      
   </script>
</html>