account/urls.py
from django.urls import path
from . import views
app_name = 'account'

urlpatterns = [
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('authorization/', views.UserAuthorizationView.as_view(), name='authorization'),
    path('<slug:slug>/setting', views.SettingView.as_view(), name='setting'),
]

construct_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name = 'construct_site'

urlpatterns = [
	path('<slug:slug>/additional/data/create/or/update',
		views.AdditionalDataCreatOrUpdateView.as_view(),
		name='additional_data_creat_or_update'),
	path('<slug:slug>/support/form/', views.SupportFormView.as_view(),
		name='support_form'),
    path('<slug:slug>/support/form/<int:pk>', views.SupportFormView.as_view(),
		name='support_form'),
    path('<slug:slug>/support/delete/<int:pk>', views.SupportDeleteView.as_view(),
		name='support_delete'),
    path('<slug:slug>/support/phone/number/<int:id>', views.SupportPhoneNumber.as_view(),
		name='support_phone_number'),
    path('<slug:slug>/faq/create/',
		views.FAQCreateView.as_view(), name='faq_create'),
	path('<slug:slug>/faq/delete/<int:pk>',
		views.FAQDeleteView.as_view(), name='faq_delete'),
	path('<slug:slug>/faq/update/<int:pk>',
		views.FAQUpdateView.as_view(), name='faq_update'),
]


construct_site_food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name = 'construct_site_food'

urlpatterns = [
	path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('apply-promocode/', views.ApplyPromoCodeView.as_view(),
		name='apply_promocode'),
	path('<slug:slug>/', views.ClientIndexView.as_view(), name='client'),
	path('<slug:slug>/construct/', views.ConstructIndexView.as_view(),
		name='construct'),
	path('<slug:slug>/good/create/', views.GoodCreateView.as_view(),
		name='good_create'),
	path('<slug:slug>/good/delete/<int:pk>', views.GoodDeleteView.as_view(),
		name='good_delete'),
	path('<slug:slug>/good/update/<int:pk>', views.GoodUpdateView.as_view(),
		name='good_update'),
	path('<slug:slug>/category/create/', views.CategoryCreateView.as_view(),
		name='category_create'),
	path('<slug:slug>/category/delete/<int:pk>', views.CategoryDeleteView.as_view(),
		name='category_delete'),
	path('<slug:slug>/category/update/<int:pk>', views.CategoryUpdateView.as_view(),
		name='category_update'),
	path('good/<int:id>/add/to/cart', views.GoodAddToCart.as_view(),
		name='good_add_to_cart'),
	path('good/<int:id>/remove/from/cart', views.GoodRemoveFromCart.as_view(),
		name='good_remove_from_cart'),
	path('order/page/<slug:slug>', views.OrderView.as_view(),
		name='order_page'),
	path('order/good/', views.OrderGoodView.as_view(),
		name='order_good'),
	path('good/list/<slug:slug>/<int:category>/',
		views.GoodListView.as_view(), name='good_list'),

]


gosite/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
	url('', include('pwa.urls')),
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(
    	redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', include('account.urls')),
    path('construct/site/', include('construct_site.urls')),
    path('', include('construct_site_food.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, 
		                 document_root=settings.MEDIA_ROOT)

construct_site_food/models.py
import contextlib
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFill
from account.models import UserSite

# Базовый mixin
class BaseMixin(models.Model):
    title = models.CharField(max_length=180)

    def __str__(self):
        return self.title

    class Meta:
    	abstract = True


# Список категории
class Category(BaseMixin):
    user_site = models.ForeignKey(
    	UserSite, on_delete=models.CASCADE,
    	null=True, blank=True,
    	related_name='category_user_sites')
    color = models.CharField(max_length=120, default="#fc8019")
    sorting = models.IntegerField(default=0)


#Список товаров
class Good(BaseMixin):
    title = models.CharField(max_length=120, null=True, blank=True)
    description = models.TextField(blank=True)
    price = models.CharField(max_length=120, blank=True, default='')
    old_price = models.CharField(max_length=120, blank=True, default='')
    photo = ProcessedImageField(upload_to='images/',
                                processors=[ResizeToFill(317, 231)],
                                format='JPEG',
                                options={'quality': 100})
    category = models.ForeignKey(Category,
    	on_delete=models.SET_NULL, null=True, blank=True)
    user_site = models.ForeignKey(
    	UserSite, on_delete=models.CASCADE,
    	related_name='good_user_sites', null=True, blank=True)
    sorting = models.IntegerField(default=0)

construct_site_food/forms.py
from string import Template
from django import forms
from django.forms import ImageField
from .models import Good


class GoodForm(forms.ModelForm):
    photo = ImageField(widget=forms.FileInput)

    class Meta:
        model = Good
        fields = (
            'title', 'price', 'old_price', 'photo',
            'category', 'description'
        )

construct_site_food/views.py
import base64
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.core.files.base import ContentFile
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView
from django.views.generic.base import TemplateResponseMixin, View
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from account.models import UserSite
from construct_site.models import Support, AdditionalData
from cart.forms import CartAddProductForm
from cart.cart import Cart
from .models import Good, Category
from django.utils import timezone
from cart.models import PromoCode, Order, OrderItem, UserPromoCodeUsage
from .forms import GoodForm
from decimal import Decimal


# Mixin для передачи url как дополнительный параметр
class UrlMixin:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url'] = self.request.GET.get('url', None)
        return context

# Mixin для отображения сообщении об успешном завершении
class DeleteMixin:

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        data = super().delete(request, *args, **kwargs)
        messages.success(self.request, self.success_message % obj.__dict__)
        return data

# Mixin товара
class GoodMixin(SuccessMessageMixin):
    model = Good
    form_class = GoodForm

    def get_success_url(self):
        slug = self.kwargs.get('slug')
        kwargs = {'slug': slug}
        return reverse_lazy('construct_site_food:construct', kwargs = kwargs)


# Mixin редактирования товара
class GoodEditMixin(GoodMixin, UrlMixin):
    template_name = 'construct_site_food/construct/good/form.html'

    def form_valid(self, form):
        slug = self.kwargs.get('slug')
        user_site = get_object_or_404(UserSite, slug=slug, user=self.request.user)
        obj = form.save(commit=False)
        obj.user_site = user_site
        obj.save()
        return super().form_valid(form)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        slug = self.kwargs.get('slug')
        form.fields['category'].queryset = Category.objects.filter(
            user_site__slug=slug)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



# Создать товар
class GoodCreateView(LoginRequiredMixin, GoodEditMixin, CreateView):
    success_message = "Товар успешно добавлен!"


# Обновить товар
class GoodUpdateView(LoginRequiredMixin, GoodEditMixin, UpdateView):
    success_message = "Товар успешно обновлен!"


# Удалить товар
class GoodDeleteView(
    LoginRequiredMixin,GoodMixin, UrlMixin, DeleteMixin, DeleteView):
    template_name = 'construct_site_food/construct/good/delete.html'
    success_message = "Товар успешно удален!"


# Mixin категорию
class CategoryMixin(SuccessMessageMixin):
    model = Category
    fields = ['title', 'sorting', 'color']

    def get_success_url(self):
        slug = self.kwargs.get('slug')
        return reverse_lazy('construct_site_food:construct', kwargs = {'slug':slug})


# Mixin редактирования категорию
class CategoryEditMixin(CategoryMixin, UrlMixin):
    template_name = 'construct_site_food/construct/category/form.html'

    def form_valid(self, form):
        slug = self.kwargs.get('slug')
        user_site = get_object_or_404(UserSite, slug=slug, user=self.request.user)
        obj = form.save(commit=False)
        obj.user_site = user_site
        obj.save()
        return super().form_valid(form)

# Создать категорию
class CategoryCreateView(
    LoginRequiredMixin, CategoryEditMixin, CreateView):
    success_message = "Категория успешно добавлена!"


# Обновить категорию
class CategoryUpdateView(
    LoginRequiredMixin, CategoryEditMixin, UpdateView):
    success_message = "Категория успешно обновлена!"


# Удалить категорию
class CategoryDeleteView(
    LoginRequiredMixin, CategoryMixin, DeleteMixin, UrlMixin, DeleteView):
    template_name = 'construct_site_food/construct/category/delete.html'
    success_message = "Категория успешно удалена!"

# Дополнительные данные создать или обновить
class AdditionalDataCreatOrUpdateView(View):

    def post(self, request, slug):
        user_site = get_object_or_404(UserSite, slug=slug, user=request.user)
        element_id = request.POST.get('element_id')
        photo = request.FILES.get('photo', None)
        value = request.POST.get('value', None)
        obj, created = AdditionalData.objects.get_or_create(
            element_id = element_id,
            user_site=user_site,
            defaults = {
                'value':value, 'element_id': element_id,
                'photo': photo, 'user_site': user_site
            }
        )
        if not created:
            obj.photo = photo
            obj.value = value
            obj.element_id = element_id
            obj.slug = user_site
            obj.save()
        return HttpResponse('saved')


# Дополнительные данные удалить
class AdditionalDataDelete(LoginRequiredMixin, View):

    def post(self, request, slug):
        element_id = request.POST.get('element_id')
        AdditionalData.objects.filter(element_id=element_id,
        	user_site__slug=slug).delete()
        return HttpResponse('deleted')


# Страница конструктора
class ConstructIndexView(LoginRequiredMixin, GoodMixin, ListView):
    template_name = 'construct_site_food/construct/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        category = self.kwargs.get('category', None)
        user_site = get_object_or_404(
            UserSite, slug=slug, user=self.request.user)
        categories = Category.objects.filter(user_site__slug=slug)
        goods = Good.objects.filter(user_site__slug=slug)
        supports = Support.objects.filter(user_site__slug=slug)
        context['user_site'] = user_site
        context['slug'] = slug
        context['categories'] = categories
        context['goods'] = goods
        context['supports'] = supports
        
        return context


# Страница клиента
class ClientIndexView(GoodMixin, View):

    def get(self, request, **kwargs):
        context = {}
        slug = self.kwargs.get('slug')
        categories = Category.objects.filter(
            user_site__slug=slug).select_related().order_by('-sorting')
        supports = Support.objects.filter(user_site__slug=slug)
        goods = Good.objects.filter(user_site__slug=slug).order_by('-sorting')
        if categories.exists():
            category = self.kwargs.get('category', None)
            if not  category:
                category = categories.first().id
            goods = goods.filter(category=category)
            context['active_category'] = category
        user_site = get_object_or_404(UserSite, slug=slug)
        context['slug'] = slug
        context['categories'] = categories
        context['goods'] = goods
        context['supports'] = supports
        context['user_site'] = user_site
        context['manifest_file'] = '/manifest/' + str(slug) + '.json'
        return render(request, user_site.site.template_name, context)


class GoodToCartMixin(View):

    def dispatch(self, *args, **kwargs):
        good_id = self.kwargs.get('id')
        self.cart = Cart(self.request)
        self.good = get_object_or_404(Good, id=good_id)
        return super().dispatch(*args, **kwargs)

# товарить товар в корзину
class GoodAddToCart(GoodToCartMixin):

    def post(self, request, *args, **kwargs):
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            self.cart.add(product=self.good,
                quantity=cd['quantity'],
                decrement=cd['decrement'])
            if self.cart.get_good(self.good):
                quantity = self.cart.get_good(self.good).get('quantity')
            else:
                quantity = 0
            return JsonResponse({
                'status': True,
                'quantity': quantity,
                'total_items': self.cart.get_items(),
                'total_price': self.cart.get_total_price()

            })
        return JsonResponse({'status': False})


# товарить товар в корзину
class GoodRemoveFromCart(GoodToCartMixin):

    def post(self, request, *args, **kwargs):
        self.cart.remove(self.good)
        return JsonResponse({'status': True})


# страница заказа
class OrderView(TemplateResponseMixin, View):
    template_name = 'construct_site_food/foodoma/order.html'

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return self.render_to_response({'slug': slug})

    def post(self, request, *args, **kwargs):
        return self.render_to_response({})

# заказать товар
class OrderGoodView(View):

    def post(self, request, *args, **kwargs):
        delivery_address = request.POST.get('delivery_address', '')
        promocode_code = request.POST.get('promocode', '')
        user = request.user
        cart = Cart(request)

        # Проверка и применение промокода
        discount_amount = Decimal('0.00')
        if promocode_code:
            try:
                promocode = PromoCode.objects.get(code=promocode_code, is_active=True, start_date__lte=timezone.now(),

templates/construct_site_food/construct/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% load static %}
  {% load construct_tags %}
    <meta charset="UTF-8">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/new-construct.css' %}">
    <link rel="stylesheet" href="{% static 'css/construct_site_default/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
<!-- Header Start -->
<header class="site-header">
  <div class="wrapper site-header__wrapper">
    <div class="site-header__start">
      <a href="#" class="brand">GOSITE</a>
    </div>
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item">
            {% condition_set request.resolver_match.url_name 'active' '' 'construct' as construct_active %}
            <a href="{% url 'construct_site_food:construct' slug=slug %}" class="{{ construct_active }}">
              Конструктор
            </a>
          </li>
          <li class="nav__item">
            {% condition_set request.resolver_match.url_name 'active' '' 'setting' as setting_active %}
            <a href="{% url 'account:setting' slug=slug %}" class="{{setting_active}}">Опубликовать</a>
          </li>
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{request.user.username}}
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <button class="dropdown-item" type="button"><a href="{% url 'logout' %}" class="exit">Выход</a>
    </div>
  </div>
</header>
<!-- Header End -->
{% block content %}
{% endblock %}

{% block modal %}
{% endblock %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/js.cookie.min.js' %}"></script>
<script src="{% static 'js/header.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/inlines.js' %}"></script>
<script type="text/Javascript">
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(document).ready(function(){
        {% block domready %}

        {% endblock %}
    });
</script>
</body>
</html>

templates/construct_site_food/construct/index.html
{% extends 'construct_site_food/construct/base.html' %}
{% load static %}
{% load construct_tags %}

<!-- Блок контента начало -->
{% block content %}
  <div class="header">
    <nav class="navbar navbar-light border-bottom" id="navbar-top">
      <div class="container">
        <div class="d-none">
          <form action="{% url 'construct_site:additional_data_creat_or_update' slug=slug %}" method="post" enctype="multipart/form-data">
            <input type="file" id="additional-photo" name="photo">
            <input type="hidden" name="element_id" value="logo">
          </form>
        </div>
        <a class="navbar-brand" href="#">
          <img src="{% get_photo 'logo' slug 'img/default_logo.png'  %}" width="30" height="30" class="d-inline-block align-top click-photo" style="border-radius: 50%;">
          <span data-id="site_text" class="logo-text additional-element" spellcheck="false" contenteditable>
            {% get_text 'site_text' slug 'Введите текст логотига' %}
          </span>
        </a>
      </div>
    </nav>
  </div>
  <section class="content">
    <div class="container">
      <div class="content-info">
        <h5 data-id="caption" class="additional-element" spellcheck="false" contenteditable>
          {% get_text 'caption' slug 'Введите загаловок!' %}
        </h5>
        {% get_text 'information' slug 'Введите информацию о компании' as information %}
        <textarea data-type="val" data-id="information" class="textarea form-control additional-element" style="height: 150px" spellcheck="false">{{information|safe}}</textarea>
        <div class="content-btn"><br>
          <div class="row">
            {% for support in supports %}
              <div class="col-md-4 col-sm-6 order-2">
                <button class="login-button d-flex justify-content-around"
                  style="background-color: {{support.bacground_color}}">
                  <span class="fa fa-whatsapp" aria-hidden="true" style="color: {{support.icon_color}}"></span>
                  <span class="text-btn" style="color: {{support.text_color}}">{{support.label}}</span>   
                  <i class="fa fa-pencil modal-display float-right" data-toggle="modal" data-target="#default-modal" data-url="{% url 'construct_site:support_form' slug=slug pk=support.id %}"></i>
                  {% if not support.is_main %}
                    <i class="fa fa-trash modal-display float-right" data-toggle="modal" data-target="#default-modal" aria-hidden="true" data-url="{% url 'construct_site:support_delete' slug=slug pk=support.id %}"></i>
                  {% endif %}
                </button>
              </div>
            {% endfor %}
            <div class="col-md-4 col-sm-6 order-1">
              <button id="support-add" class="new-btn modal-display " data-toggle="modal" data-target="#default-modal" aria-hidden="true" data-url="{% url 'construct_site:support_form' slug=slug %}">
                Добавить whatsapp
              </button>
            </div>
        </div>
      </div>
    </div>
  </section>
  <section class="content-2">
    <div class="container">
      <div class="content-product">
          <div class="row">
            <div class="col-md-4">
              <button class="new-btn modal-display" data-toggle="modal" data-target="#default-modal" 
                aria-hidden="true" data-url="{% url 'construct_site_food:category_create' slug=slug %}">
                Добавить категорию
              </button>
            </div>
            <div class="col-md-8">
              <div class="" style="margin: 5px 0;">
                {% for category in categories %}
                  <output class="category-label category category-label-mob" data-id="{{category.id}}"  contenteditable="">
                    {{category.title|cut:' '}}
                  </output>
                  <output class="category-label category-label-icon modal-display" aria-hidden="true" data-toggle="modal" data-target="#default-modal" aria-hidden="true"   data-url="{% url 'construct_site_food:category_delete' slug=slug pk=category.id %}">
                    <i class="fa-icon-category fa fa fa-trash"></i>
                  </output>
                  <output class="category-label category-label-icon modal-display m-16" aria-hidden="true" data-toggle="modal" data-target="#default-modal" aria-hidden="true"   data-url="{% url 'construct_site_food:category_update' slug=slug pk=category.id %}">
                    <i class="fa fa-pencil"></i>
                  </output>         
                {% endfor %}
              </div>
            </div>
        </div>

        <div class="content-detail">
          <div class="row">
            <div class="col-lg-4 col-sm-6">
              <div class="add modal-display" data-toggle="modal" data-target="#default-modal" aria-hidden="true"   data-url="{% url 'construct_site_food:good_create' slug=slug %}">
                <div class="add-images">
                  <label>Добавить товар </label>
                </div>
              </div>
            </div>
            {% for good in goods %}
            <div class="col-lg-4 col-sm-6">
              <div class="product-item">
                <div class="pi-pic">
                  {% if not good.category and categories.exists %}
                  <div class="tag-sale modal-display" data-toggle="modal" data-target="#default-modal" data-url="{% url 'construct_site_food:good_update' slug=slug pk=good.id %}">Укажите категорию</div>
                  {% endif %}

                    <picture class="img-fluid">
                        <img
                            src="{{ good.photo.url }}"
                            class="img-fluid"
                        />
                    </picture>
                  <div class="pi-links">
                    <button class="wishlist-btn modal-display" data-toggle="modal" data-target="#default-modal" data-url="{% url 'construct_site_food:good_update' slug=slug pk=good.id %}">
                      <i class="fa fa-pencil"></i>
                    </button>
                    <button class="wishlist-btn modal-display" data-toggle="modal" data-target="#default-modal" data-url="{% url 'construct_site_food:good_delete' slug=slug pk=good.id %}">
                      <i class="fa fa fa-trash" aria-hidden="true"></i>
                    </button>
                  </div>
                </div>
                <div class="btn-product">
                  <div class="btn-group" align="center">
                    Название: {{good.title}}
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
              <div class="col-lg-4 col-sm-6">
                У вас нет добавленных продуктов!
              </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </section>

  {% if messages %}
    {% for message in messages %}
      <div id="toastsContainerTopRight" class="toasts-top-right fixed">
        <div class="alert alert-info alert-with-icon" data-notify="container">
          <i class="fa fa-bell-o" aria-hidden="true" data-notify="icon"></i>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          <span data-notify="message">{{ message.message }}</span>
        </div>
      </div>
    {% endfor %}
{% endif %}
  <!-- alert begin -->
  
  <!-- alert begin -->

  <!-- Modal begin -->
  <div class="modal fade" id="designModal" tabindex="-1" role="dialog" aria-labelledby="designModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="design-content" class="modal-body"></div>
      </div>
    </div>
  </div>
  <!-- Modal end -->
{% endblock %}
<!-- Блок контента конец -->

<!-- Блок модуля начало -->
{% block modal %}
  <!-- Modal default -->
  <div class="modal fade" id="default-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header border-bottom-none">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="modal-content"></div>        
      </div>
    </div>
  </div>
  <!-- Modal default end -->
{% endblock %}
<!-- Блок модуля конец -->

<!-- Блок js начало -->
{% block domready %}
  
  $(window).scroll(function () {
    sessionStorage.scrollTop = $(this).scrollTop();
  })

  if (sessionStorage.scrollTop != "undefined") {
    $(window).scrollTop(sessionStorage.scrollTop);
  }

  $(document).on("click", ".modal-display", function() {
    var url = $(this).data('url')
    $.ajax({
      url: url,
      type: 'GET',
      data:{url: url},
      error: function(jqXHR, textStatus, errorThrown) {
          alert(jqXHR.responseText)
      },
      success:function (data) {
          $('#modal-content').html(data)
      }
    })
  })

  $(document).on("change", "#id_type", function() {
    var id = $(this).val()
    if(id==2){
      $('#design_text-content').removeClass('d-none')
      $('#order_text-content').removeClass('d-none')
      $('.select-font').removeClass('d-none')
      $('.select-img').addClass('d-none')
    }
    else if(id==3){
      $('#design_text-content').removeClass('d-none')
      $('#order_text-content').removeClass('d-none')
      $('.select-font').addClass('d-none')
      $('.select-img').removeClass('d-none')
    }
    else{
      $('#design_text-content').addClass('d-none')
      $('#order_text-content').removeClass('d-none')
      $('.select-font').addClass('d-none')
      $('.select-img').addClass('d-none')
    }
  })

  $(document).on("change", "#id_indicate_price", function() {
    if($(this).is(':checked')){
      $('#price-content').removeClass('d-none')
    }
    else{
      $('#price-content').addClass('d-none')
    }
  })

  $(document).on("blur", ".additional-element", function() {
    var type = $(this).data('type')
    var element_id = $(this).data('id')
    if(type == 'val'){
      var value = $(this).val()
    }
    else{
      var value = $(this).text().trim()
    }
    $.ajax({
      url: "{% url 'construct_site:additional_data_creat_or_update' slug=slug %}",
      method: "POST",
      data: {
        value: value,
        element_id: element_id
      },
      success: function(data){
      }
    })
  })

  $(document).on("click", ".tab-good", function() {
    var validate = true
    var type = $('#id_type').val()
    var font = $('#id_font').val()
    var photo = $('#id_photo').val()
    var photo_exists = $('#photo-exists').val()
    var next = $(this).data('next')
    if(type == 2 && !font){
      $('#id_font').addClass('error-color')
      validate = false
    }
    if(!photo_exists && !photo){
      $('#id_photo').addClass('error-color')
      validate = false
    }
    if(validate){
      $("#profile-tab").trigger("click")
    }
  })
  
  $(document).on("change", "#id_photo, #id_font", function() {
    var font = $('#id_font').val()
    var photo_exists = $('#photo-exists').val()
    var photo = $('#id_photo').val()
    if(font){
      $('#id_font').removeClass('error-color')
    }
    else{
      $('#id_font').addClass('error-color')
    }
    if(!photo_exists && !photo){
      $('#id_photo').addClass('error-color')
    }
    else{
      $('#id_photo').removeClass('error-color')
    }
  })

  $(document).on("click", ".click-photo", function() {
    $('#additional-photo').trigger('click')
  })

  $(document).on("change", "#additional-photo", function() {
    var form = $(this).closest('form')
    var data = new FormData(form.get(0));
    $.ajax({
      url: form.attr('action'),
      method: "POST",
      data: data,
      processData: false,
      contentType: false,
      success:function (data) {
        location.reload()
      }
    })
  })    
{% endblock %}
<!-- Блок js конец -->